web/coordinates/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import user_passes_test

app_name = 'coordinates'

urlpatterns = [
    # /coordinates/
    url(r'^$', views.index, name='index'),

    # /coordinates/coordinatesystem/
    url(r'coordinatesystem/$', (user_passes_test(lambda u: u.is_staff))(views.CoordinateSystemListView.as_view()), name='coordinatesystem'),

    # /coordinates/coordinatesystem/712/
    url(r'^coordinatesystem/(?P<pk>[0-9]+)/$', (user_passes_test(lambda u: u.is_staff))(views.CoordinateSystemDetailView.as_view()), name='coordinatesystem_detail'),

    # /coordinates/coordinatesystem/create/
    url(r'coordinatesystem/create/$', (user_passes_test(lambda u: u.is_staff))(views.CoordinateSystemCreateView.as_view()), name='coordinatesystem_create'),

    # /coordinates/coordinatesystem/update/712/
    url(r'^coordinatesystem/update/(?P<pk>[0-9]+)/$', (user_passes_test(lambda u: u.is_staff))(views.CoordinateSystemUpdateView.as_view()), name='coordinatesystem_update'),

    # /coordinates/coordinatesystem/delete/712/
    url(r'^coordinatesystem/delete/(?P<pk>[0-9]+)/$', (user_passes_test(lambda u: u.is_staff))(views.CoordinateSystemDeleteView.as_view()), name='coordinatesystem_delete'),
]

web/esnow/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    url(r'^', include('home.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('coordinates/', include('coordinates.urls')),
    path('modis/', include('modis.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

web/home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    # /
    url(r'^$', views.index, name='index'),
]

web/coordinates/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class CoordinateSystem(models.Model):
    name = models.CharField(max_length=1000)

    def get_absolute_url(self):
        return reverse('coordinates:coordinatesystem_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name

web/coordinates/views.py
from django.views import generic
from django.http import HttpResponse
from django.template import loader
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import CoordinateSystem

def index(request):
    context = {}
    template = loader.get_template('coordinates/index.html')
    return HttpResponse(template.render(context, request))

class CoordinateSystemListView(generic.ListView):
    template_name = 'coordinates/coordinatesystem/index.html'
    context_object_name = 'coordinatesystems'

    def get_queryset(self):
        return CoordinateSystem.objects.all()

class CoordinateSystemDetailView(generic.DetailView):
    model = CoordinateSystem
    template_name = 'coordinates/coordinatesystem/detail.html'

class CoordinateSystemCreateView(CreateView):
    model = CoordinateSystem
    fields = ['name']

class CoordinateSystemUpdateView(UpdateView):
    model = CoordinateSystem
    fields = ['name']

class CoordinateSystemDeleteView(DeleteView):
    model = CoordinateSystem
    success_url = reverse_lazy('coordinates:coordinatesystem')

web/coordinates/templates/coordinates/coordinatesystem/detail.html
{% extends 'base.html' %}
{% block title %}
    CoordinateSystem
{% endblock %}
{% block body %}
    <h1>
        {{ coordinatesystem.name }}
    </h1>
{% endblock %}

web/coordinates/templates/coordinates/coordinatesystem/index.html
{% extends 'base.html' %}
{% block title %}
    CoordinateSystems
{% endblock %}
{% block body %}
    <h3>
        CoordinateSystems
    </h3>
    <a href="{% url 'coordinates:coordinatesystem_create' %}">
        Создать CoordinateSystem
    </a>
    {% if coordinatesystems %}
    <ul>
        {% for coordinatesystem in coordinatesystems %}
        <li>
            <!-- Detail -->
            <a href="{% url 'coordinates:coordinatesystem_detail' coordinatesystem.id %}" class="btn btn-default btn-sm">
                {{ coordinatesystem.name }}
                <span class="glyphicon glyphicon-info-sign"></span>
            </a>

            <!-- Update -->
            <a href="{% url 'coordinates:coordinatesystem_update' coordinatesystem.id %}" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-edit"></span>
            </a>

            <!-- Delete -->
            <form action="{% url 'coordinates:coordinatesystem_delete' coordinatesystem.id %}" method="post" style="display: inline-block">
                {% csrf_token %}
                <input type="hidden" name="coordinatesystem_id" value="{{ coordinatesystem.id }}" />
                <button type="submit" class="btn btn-default btn-sm">
                    <span class="glyphicon glyphicon-trash"></span>
                </button>
            </form>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <h3>
        Нет данных
    </h3>
    {% endif %}
{% endblock %}