web/coordinates/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import user_passes_test

app_name = 'coordinates'

urlpatterns = [
    # /coordinates/
    url(r'^$', views.index, name='index'),

    # /coordinates/coordinatesystem/
    url(r'coordinatesystem/$', (user_passes_test(lambda u: u.is_staff))(views.CoordinateSystemListView.as_view()), name='coordinatesystem'),

    # /coordinates/coordinatesystem/712/
    url(r'^coordinatesystem/(?P<pk>[0-9]+)/$', (user_passes_test(lambda u: u.is_staff))(views.CoordinateSystemDetailView.as_view()), name='coordinatesystem_detail'),

    # /coordinates/coordinatesystem/create/
    url(r'coordinatesystem/create/$', (user_passes_test(lambda u: u.is_staff))(views.CoordinateSystemCreateView.as_view()), name='coordinatesystem_create'),

    # /coordinates/coordinatesystem/update/712/
    url(r'^coordinatesystem/update/(?P<pk>[0-9]+)/$', (user_passes_test(lambda u: u.is_staff))(views.CoordinateSystemUpdateView.as_view()), name='coordinatesystem_update'),

    # /coordinates/coordinatesystem/delete/712/
    url(r'^coordinatesystem/delete/(?P<pk>[0-9]+)/$', (user_passes_test(lambda u: u.is_staff))(views.CoordinateSystemDeleteView.as_view()), name='coordinatesystem_delete'),
]

web/esnow/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    url(r'^', include('home.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('coordinates/', include('coordinates.urls')),
    path('modis/', include('modis.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

web/home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    # /
    url(r'^$', views.index, name='index'),
]

web/modis/urls.py
# git test

from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import user_passes_test

app_name = 'modis'

urlpatterns = [
    # /modis/
    url(r'^$', (user_passes_test(lambda u: u.is_staff))(views.index), name='index'),

    # /modis/source/
    url(r'source/$', (user_passes_test(lambda u: u.is_staff))(views.SourceListView.as_view()), name='source'),

    # /modis/source/712/
    url(r'^source/(?P<pk>[0-9]+)/$', (user_passes_test(lambda u: u.is_staff))(views.SourceDetailView.as_view()), name='source_detail'),

    # /modis/source/create/
    url(r'source/create/$', (user_passes_test(lambda u: u.is_staff))(views.SourceCreateView.as_view()), name='source_create'),

    # /modis/source/update/712/
    url(r'^source/update/(?P<pk>[0-9]+)/$', (user_passes_test(lambda u: u.is_staff))(views.SourceUpdateView.as_view()), name='source_update'),

    # /modis/source/delete/712/
    url(r'^source/delete/(?P<pk>[0-9]+)/$', (user_passes_test(lambda u: u.is_staff))(views.SourceDeleteView.as_view()), name='source_delete'),

    # /modis/product/
    url(r'product/$', (user_passes_test(lambda u: u.is_staff))(views.ProductListView.as_view()), name='product'),

    # /modis/product/712/
    url(r'^product/(?P<pk>[0-9]+)/$', (user_passes_test(lambda u: u.is_staff))(views.ProductDetailView.as_view()), name='product_detail'),

    # /modis/product/create/
    url(r'product/create/$', (user_passes_test(lambda u: u.is_staff))(views.ProductCreateView.as_view()), name='product_create'),

    # /modis/product/update/712/
    url(r'^product/update/(?P<pk>[0-9]+)/$', (user_passes_test(lambda u: u.is_staff))(views.ProductUpdateView.as_view()), name='product_update'),

    # /modis/product/delete/712/
    url(r'^product/delete/(?P<pk>[0-9]+)/$', (user_passes_test(lambda u: u.is_staff))(views.ProductDeleteView.as_view()), name='product_delete'),

    # /modis/dataset/
    url(r'dataset/$', (user_passes_test(lambda u: u.is_staff))(views.DataSetListView.as_view()), name='dataset'),

    # /modis/dataset/712/
    url(r'^dataset/(?P<pk>[0-9]+)/$', (user_passes_test(lambda u: u.is_staff))(views.DataSetDetailView.as_view()), name='dataset_detail'),

    # /modis/dataset/create/
    url(r'dataset/create/$', (user_passes_test(lambda u: u.is_staff))(views.DataSetCreateView.as_view()), name='dataset_create'),

    # /modis/dataset/update/712/
    url(r'^dataset/update/(?P<pk>[0-9]+)/$', (user_passes_test(lambda u: u.is_staff))(views.DataSetUpdateView.as_view()), name='dataset_update'),

    # /modis/dataset/delete/712/
    url(r'^dataset/delete/(?P<pk>[0-9]+)/$', (user_passes_test(lambda u: u.is_staff))(views.DataSetDeleteView.as_view()), name='dataset_delete'),

    # /modis/span/
    url(r'span/$', (user_passes_test(lambda u: u.is_staff))(views.SpanListView.as_view()), name='span'),

    # /modis/span/712/
    url(r'^span/(?P<pk>[0-9]+)/$', (user_passes_test(lambda u: u.is_staff))(views.SpanDetailView.as_view()), name='span_detail'),

    # /modis/span/create/
    url(r'span/create/$', (user_passes_test(lambda u: u.is_staff))(views.SpanCreateView.as_view()), name='span_create'),

    # /modis/span/update/712/
    url(r'^span/update/(?P<pk>[0-9]+)/$', (user_passes_test(lambda u: u.is_staff))(views.SpanUpdateView.as_view()), name='span_update'),

    # /modis/span/delete/712/
    url(r'^span/delete/(?P<pk>[0-9]+)/$', (user_passes_test(lambda u: u.is_staff))(views.SpanDeleteView.as_view()), name='span_delete'),

    # /modis/getmodis
    url(r'getmodis/$', (user_passes_test(lambda u: u.is_staff))(views.GetMODIS), name='getmodis'),

    # /modis/viewmodis
    url(r'viewmodis/$', (user_passes_test(lambda u: u.is_staff))(views.ViewMODIS), name='viewmodis'),

    # /modis/getyears
    url(r'getyears/$', (user_passes_test(lambda u: u.is_staff))(views.GetYears), name='getyears'),

    # /modis/getdaysyears
    url(r'getdaysyears/$', (user_passes_test(lambda u: u.is_staff))(views.GetDaysYears), name='getdaysyears'),
]

web/users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'

urlpatterns = [
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
]

web/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            ESnow
        {% endblock %}
    </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

{#    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">#}
{#    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>#}
{#    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>#}
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home:index' %}">ESnow</a>
        </div>
        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li>
                    <a href="{% url 'modis:index' %}">
                        <span class="glyphicon glyphicon-th-large" aria-hidden="true"></span>&nbsp; Modis
                    </a>
                </li>
                <li>
                    <a href="{% url 'coordinates:index' %}">
                        <span class="glyphicon glyphicon-th-large" aria-hidden="true"></span>&nbsp; CoordinateSystem
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li>
                        <a href="#">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; {{ user.username }}
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'logout' %}">
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Выйти
                        </a>
                    </li>
                {% else %}
                    <li>
                        <a href="{% url 'users:register' %}">
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Регистрация
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'login' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Войти
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

web/templates/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">
                {{ field.errors }}
            </span>
        </div>
        <label class="control-label col-sm-2">
            {{ field.label_tag }}
        </label>
        <div class="col-sm-10">
            {{ field }}
        </div>
    </div>
{% endfor %}