web/esnow/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    url(r'^', include('home.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('coordinates/', include('coordinates.urls')),
    path('modis/', include('modis.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

web/home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    # /
    url(r'^$', views.index, name='index'),
]

web/modis/urls.py
# git test

from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import user_passes_test

app_name = 'modis'

urlpatterns = [
    # /modis/
    url(r'^$', (user_passes_test(lambda u: u.is_staff))(views.index), name='index'),

    # /modis/source/
    url(r'source/$', (user_passes_test(lambda u: u.is_staff))(views.SourceListView.as_view()), name='source'),

    # /modis/source/712/
    url(r'^source/(?P<pk>[0-9]+)/$', (user_passes_test(lambda u: u.is_staff))(views.SourceDetailView.as_view()), name='source_detail'),

    # /modis/source/create/
    url(r'source/create/$', (user_passes_test(lambda u: u.is_staff))(views.SourceCreateView.as_view()), name='source_create'),

    # /modis/source/update/712/
    url(r'^source/update/(?P<pk>[0-9]+)/$', (user_passes_test(lambda u: u.is_staff))(views.SourceUpdateView.as_view()), name='source_update'),

    # /modis/source/delete/712/
    url(r'^source/delete/(?P<pk>[0-9]+)/$', (user_passes_test(lambda u: u.is_staff))(views.SourceDeleteView.as_view()), name='source_delete'),

    # /modis/product/
    url(r'product/$', (user_passes_test(lambda u: u.is_staff))(views.ProductListView.as_view()), name='product'),

    # /modis/product/712/
    url(r'^product/(?P<pk>[0-9]+)/$', (user_passes_test(lambda u: u.is_staff))(views.ProductDetailView.as_view()), name='product_detail'),

    # /modis/product/create/
    url(r'product/create/$', (user_passes_test(lambda u: u.is_staff))(views.ProductCreateView.as_view()), name='product_create'),

    # /modis/product/update/712/
    url(r'^product/update/(?P<pk>[0-9]+)/$', (user_passes_test(lambda u: u.is_staff))(views.ProductUpdateView.as_view()), name='product_update'),

    # /modis/product/delete/712/
    url(r'^product/delete/(?P<pk>[0-9]+)/$', (user_passes_test(lambda u: u.is_staff))(views.ProductDeleteView.as_view()), name='product_delete'),

    # /modis/dataset/
    url(r'dataset/$', (user_passes_test(lambda u: u.is_staff))(views.DataSetListView.as_view()), name='dataset'),

    # /modis/dataset/712/
    url(r'^dataset/(?P<pk>[0-9]+)/$', (user_passes_test(lambda u: u.is_staff))(views.DataSetDetailView.as_view()), name='dataset_detail'),

    # /modis/dataset/create/
    url(r'dataset/create/$', (user_passes_test(lambda u: u.is_staff))(views.DataSetCreateView.as_view()), name='dataset_create'),

    # /modis/dataset/update/712/
    url(r'^dataset/update/(?P<pk>[0-9]+)/$', (user_passes_test(lambda u: u.is_staff))(views.DataSetUpdateView.as_view()), name='dataset_update'),

    # /modis/dataset/delete/712/
    url(r'^dataset/delete/(?P<pk>[0-9]+)/$', (user_passes_test(lambda u: u.is_staff))(views.DataSetDeleteView.as_view()), name='dataset_delete'),

    # /modis/span/
    url(r'span/$', (user_passes_test(lambda u: u.is_staff))(views.SpanListView.as_view()), name='span'),

    # /modis/span/712/
    url(r'^span/(?P<pk>[0-9]+)/$', (user_passes_test(lambda u: u.is_staff))(views.SpanDetailView.as_view()), name='span_detail'),

    # /modis/span/create/
    url(r'span/create/$', (user_passes_test(lambda u: u.is_staff))(views.SpanCreateView.as_view()), name='span_create'),

    # /modis/span/update/712/
    url(r'^span/update/(?P<pk>[0-9]+)/$', (user_passes_test(lambda u: u.is_staff))(views.SpanUpdateView.as_view()), name='span_update'),

    # /modis/span/delete/712/
    url(r'^span/delete/(?P<pk>[0-9]+)/$', (user_passes_test(lambda u: u.is_staff))(views.SpanDeleteView.as_view()), name='span_delete'),

    # /modis/getmodis
    url(r'getmodis/$', (user_passes_test(lambda u: u.is_staff))(views.GetMODIS), name='getmodis'),

    # /modis/viewmodis
    url(r'viewmodis/$', (user_passes_test(lambda u: u.is_staff))(views.ViewMODIS), name='viewmodis'),

    # /modis/getyears
    url(r'getyears/$', (user_passes_test(lambda u: u.is_staff))(views.GetYears), name='getyears'),

    # /modis/getdaysyears
    url(r'getdaysyears/$', (user_passes_test(lambda u: u.is_staff))(views.GetDaysYears), name='getdaysyears'),
]

web/modis/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Source(models.Model):
    name = models.CharField(max_length=1000)

    def get_absolute_url(self):
        return reverse('modis:source_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=1000)
    source = models.ForeignKey(Source, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('modis:product_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name

class DataSet(models.Model):
    index = models.IntegerField()
    name = models.CharField(max_length=1000)
    data_type = models.CharField(max_length=1000)
    dimensions = models.IntegerField()
    fill_value = models.IntegerField()
    valid_range = models.IntegerField()
    cell_area = models.DecimalField(decimal_places=7, max_digits=9, blank=True, null=True)

    # description = models.CharField(max_length=1000)
    # units = models.CharField(max_length=1000)
    # fill_value = models.CharField(max_length=1000)
    # valid_range = models.CharField(max_length=1000)
    # scaling_factor = models.CharField(max_length=1000)

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    # source = models.ForeignKey(Product.source, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('modis:dataset_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name

class Span(models.Model):
    name = models.CharField(max_length=1000)

    def get_absolute_url(self):
        return reverse('modis:span_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name

web/modis/views.py
from django.views import generic
from django.http import HttpResponse
from django.template import loader
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
import subprocess
import datetime
import glob
import os
import ntpath
import shutil
from django.http import JsonResponse
from .models import Source, Product, DataSet, Span
import constants

def index(request):
    context = {}
    template = loader.get_template('modis/index.html')
    return HttpResponse(template.render(context, request))

class SourceListView(generic.ListView):
    template_name = 'modis/source/index.html'
    context_object_name = 'sources'

    def get_queryset(self):
        return Source.objects.all()

class SourceDetailView(generic.DetailView):
    model = Source
    template_name = 'modis/source/detail.html'

class SourceCreateView(CreateView):
    model = Source
    fields = ['name']

class SourceUpdateView(UpdateView):
    model = Source
    fields = ['name']

class SourceDeleteView(DeleteView):
    model = Source
    success_url = reverse_lazy('modis:source')

class ProductListView(generic.ListView):
    template_name = 'modis/product/index.html'
    context_object_name = 'products'

    def get_queryset(self):
        return Product.objects.all()

class ProductDetailView(generic.DetailView):
    model = Product
    template_name = 'modis/product/detail.html'

class ProductCreateView(CreateView):
    model = Product
    fields = ['name', 'source']

class ProductUpdateView(UpdateView):
    model = Product
    fields = ['name', 'source']

class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('modis:product')

class DataSetListView(generic.ListView):
    template_name = 'modis/dataset/index.html'
    context_object_name = 'datasets'

    def get_queryset(self):
        return DataSet.objects.all()

class DataSetDetailView(generic.DetailView):
    model = DataSet
    template_name = 'modis/dataset/detail.html'

class DataSetCreateView(CreateView):
    model = DataSet
    fields = ['index', 'name', 'data_type',
              'fill_value', 'valid_range', 'product']

class DataSetUpdateView(UpdateView):
    model = DataSet
    fields = ['index', 'name', 'data_type',
              'fill_value', 'valid_range', 'product']

class DataSetDeleteView(DeleteView):
    model = DataSet
    success_url = reverse_lazy('modis:dataset')

class SpanListView(generic.ListView):
    template_name = 'modis/span/index.html'
    context_object_name = 'spans'

    def get_queryset(self):
        return Span.objects.all()

class SpanDetailView(generic.DetailView):
    model = Span
    template_name = 'modis/span/detail.html'

class SpanCreateView(CreateView):
    model = Span
    fields = ['name']

class SpanUpdateView(UpdateView):
    model = Span
    fields = ['name']

class SpanDeleteView(DeleteView):
    model = Span
    success_url = reverse_lazy('modis:span')

def ViewMODIS(request):
    datasets = DataSet.objects.all()
    years = [1, 2, 3, 4]
    context = {
        'datasets': datasets,
        'years': years,
        'geoserver_url': constants.geoserver_url,
        'geoserver_workspace_name': constants.geoserver_workspace_name
    }
    template = loader.get_template('modis/VewMODIS.html')
    return HttpResponse(template.render(context, request))

def GetYears(request):
    if request.method == "GET":
        dataset = DataSet.objects.filter(pk=request.GET.get('dataset_id', None))[0]
        years = []
        for file in glob.glob(constants.geoserver_workspace_folder + "\\" + dataset.product.name + r'\\*.tif'):
            file_date = os.path.splitext(ntpath.basename(file))[0][-7:]
            file_year = file_date[:4]
            years.append(file_year)
        years = list(dict.fromkeys(years))
        data = {
            "message": "Message: " + dataset.name,
            "years": years}
        return JsonResponse(data)
    else:
        return JsonResponse({})

def GetDaysYears(request):
    if request.method == "GET":
        dataset = DataSet.objects.filter(pk=request.GET.get('dataset_id', None))[0]
        year = request.GET.get('year', None)
        daysyears = []
        for file in glob.glob(constants.geoserver_workspace_folder + "\\" + dataset.product.name + r'\\*.tif'):
            file_date = os.path.splitext(ntpath.basename(file))[0][-7:]
            file_year = file_date[:4]
            if file_year == year:
                daysyears.append(file_date[-3:])
        daysyears = list(dict.fromkeys(daysyears))
        data = {
            "message": "Message: OK",
            "daysyears": daysyears}
        return JsonResponse(data)
    else:
        return JsonResponse({})

def GetMODIS(request):
    context = {}
    template = loader.get_template('modis/GetMODIS.html')
    if request.method == 'POST':
        if os.listdir(constants.modis_folder_download):
            return HttpResponse(template.render(context, request))
        spans = ""
        for span in Span.objects.all():
            spans += span.name + ","
        spans = spans[:-1]
        for dataset in DataSet.objects.all():
            year_last = int(constants.modis_first_date[:4])
            month_last = int(constants.modis_first_date[:7][-2:])
            day_last = int(constants.modis_first_date[-2:]) - 1
            day_of_year_last = (
                datetime.datetime(year=year_last, month=month_last, day=day_last)
                - datetime.datetime(year_last, 1, 1)).days + 1
            for file in glob.glob(constants.geoserver_workspace_folder + "\\" + dataset.product.name + r'\\*.tif'):
                file_date = os.path.splitext(ntpath.basename(file))[0][-7:]
                file_year = file_date[:4]
                file_day_of_year = file_date[-3:]
                if int(file_year) >= year_last and int(file_day_of_year) >= day_of_year_last:
                    year_last = int(file_year)
                    day_of_year_last = int(file_day_of_year)
            date_last = datetime.datetime(year_last, 1, 1) + datetime.timedelta(day_of_year_last)

            proc_download =\
                subprocess.Popen("cmd.exe /c modis_download.py -U "
                                 + constants.modis_user
                                 + " -P "
                                 + constants.modis_password
                                 + " -r -u https://n5eil01u.ecs.nsidc.org -s "
                                 + dataset.product.source.name
                                 + " -p "
                                 + dataset.product.name
                                 + " -t "
                                 + spans
                                 + " -f "
                                 + date_last.strftime("%Y-%m-%d")
                                 + " -e "
                                 + datetime.datetime.now().strftime("%Y-%m-%d")
                                 # + "2018-12-31"
                                 + " "
                                 + constants.modis_folder_download,
                                 cwd=constants.modis_folder_download,
                                 shell=True)
            proc_download.wait()
            proc_mosaic =\
                subprocess.Popen(r"cmd.exe /c modis_mosaic.py -o "
                                 + constants.modis_filename_mosaic
                                 + r" -s " + "\""
                                 + str(dataset.index)
                                 + "\" "
                                 + constants.modis_folder_download
                                 + r"\listfile"
                                 + dataset.product.name
                                 + r".txt",
                                 cwd=constants.modis_folder_download,
                                 shell=True)
            proc_mosaic.wait()

            if not os.path.exists(constants.geoserver_workspace_folder
                    + "\\"
                    + dataset.product.name):
                os.makedirs(constants.geoserver_workspace_folder
                    + "\\"
                    + dataset.product.name)

            for file in glob.glob(constants.modis_folder_download + r'\\*.tif'):
                proc_reproject = subprocess.Popen(
                    r"cmd.exe /c modis_convert.py -v -s " + "\"( "
                    + str(dataset.index)
                    + " )\"" + r" -o "
                    + dataset.name + r"_" + os.path.splitext(ntpath.basename(file))[0][:-1]
                    + r" -e "
                    + constants.modis_projection
                    + r" "
                    + file,
                    cwd=constants.modis_folder_download,
                    shell=True)
                proc_reproject.wait()
                shutil.move(
                    constants.modis_folder_download
                    + "\\"
                    + dataset.name
                    + r"_"
                    + os.path.splitext(ntpath.basename(file))[0][:-1] + ".tif",
                    constants.geoserver_workspace_folder
                    + "\\"
                    + dataset.product.name
                    + "\\"
                    + dataset.name
                    + r"_"
                    + os.path.splitext(ntpath.basename(file))[0][:-1] + ".tif")

                proc_publish_store = subprocess.Popen(
                    r"cmd.exe /c curl -v -u "
                    + constants.geoserver_user
                    + r":"
                    + constants.geoserver_password
                    + r" -POST -H "
                    + "\"Content-type: text/xml\" -d \"<coverageStore><name>"
                    + dataset.name
                    + r"_"
                    + os.path.splitext(ntpath.basename(file))[0][:-1]
                    + "</name><type>GeoTIFF</type><enabled>true</enabled><workspace>"
                    + constants.geoserver_workspace_name

web/modis/templates/modis/GetMODIS.html
{% extends 'base.html' %}
{% block title %}
    Получить снимки MODIS и опубликовать их
{% endblock %}
{% block body %}
    <h3>
        Получить снимки MODIS и опубликовать их
    </h3>
    <form class="form-horizontal" action="" method="post">
        {% csrf_token %}
{#        {% include 'form-template.html' %}#}
{#        <h3>{{ test }}</h3>#}
        <button type="submit" class="btn btn-success">Запуск</button>
    </form>
{% endblock %}

web/modis/templates/modis/VewMODIS.html
{% extends 'base.html' %}
{% block title %}
    Просмотр снимков
{% endblock %}
{% block body %}
    <link rel="stylesheet" href="https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v5.3.0/css/ol.css" type="text/css">
    <style>
        .map {
            width: 100%;
        }
    </style>
    <script src="https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v5.3.0/build/ol.js"></script>
    <h3>
        Просмотр снимков
    </h3>
    <label>DataSet:</label>
    <select id="dataset" onchange="ChangeDataSet()">
        {% for dataset in datasets %}
            <option value="{{ dataset.id }}">{{ dataset.name }}</option>
        {% endfor %}
    </select>
    <label>Год:</label>
    <select id="year" onchange="ChangeYear()">
    </select>
    <label>День (в году):</label>
    <select id="day_year" onchange="ChangeLayer()">
    </select>
    <div id="map" class="map"></div>

    <script type="text/javascript">
        var geoserver_url = "{{ geoserver_url }}",
            geoserver_workspace_name = "{{ geoserver_workspace_name }}";

        var Source_MODIS = new ol.source.TileWMS({
            url: geoserver_url + '/geoserver/' + geoserver_workspace_name + '/wms?',
            params: {
                'LAYERS': geoserver_workspace_name + ':_',
                'VERSION': '1.1.1',
                'FORMAT': 'image/png',
                'TILED': true
            },
            serverType: 'geoserver'
        });
        var Layer_MODIS = new ol.layer.Tile({
            source: Source_MODIS
        });
        Layer_MODIS.setOpacity(0.80);

        var map = new ol.Map({
            target: 'map',
            layers: [
                new ol.layer.Tile({
                    source: new ol.source.OSM()
                }),
                Layer_MODIS],
            view: new ol.View({
                center: ol.proj.fromLonLat([66.902, 48.714]),
                zoom: 5
            })});

        function ChangeDataSet(){
            $.ajax({
                url: "/modis/getyears/",
                data: { "dataset_id": $('#dataset').val() },
                success: function (data) {
                    var $dropdown = $("#year");
                    $dropdown.find('option').remove();
                    $.each(data.years, function () {
                        $dropdown.append($("<option />").val(this).text(this));
                    });
                    ChangeYear();
                },
                error: function () {
                    alert("Error")
                }
            });
        }

        function ChangeYear(){
            $.ajax({
                url: "/modis/getdaysyears/",
                data: {
                    "dataset_id": $('#dataset').val(),
                    "year": $('#year').val()},
                success: function (data) {
                    var $dropdown = $("#day_year");
                    $dropdown.find('option').remove();
                    $.each(data.daysyears, function () {
                        $dropdown.append($("<option />").val(this).text(this));
                    });
                    ChangeLayer();
                },
                error: function () {
                    alert("Error")
                }
            });
        }

        function ChangeLayer(){
            var layer_name = $('#dataset option:selected').text()
                + "_A"
                + $('#year').val()
                + $('#day_year').val();
            $('#test').val(layer_name);
            var Source_MODIS_New = new ol.source.TileWMS({
                url: geoserver_url + '/geoserver/' + geoserver_workspace_name + '/wms?',
                params: {
                    'LAYERS': geoserver_workspace_name + ':' + layer_name,
                    'VERSION': '1.1.1',
                    'FORMAT': 'image/png',
                    'TILED': true
                },
                serverType: 'geoserver'
                });
            Layer_MODIS.setSource(Source_MODIS_New);
        }

        $( document ).ready(function() {
            ChangeDataSet();
        });
    </script>
{% endblock %}

web/modis/templates/modis/dataset_form.html
{% extends 'base.html' %}
{% block title %}
    Создать DataSet
{% endblock %}
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <form class="form-horizontal" action="" method="post">
                            {% csrf_token %}
                            {% include 'form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Сохранить</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

web/modis/templates/modis/index.html
{% extends 'base.html' %}
{% block title %}
    Modis
{% endblock %}
{% block body %}
    <h3>
        Modis
    </h3>
    <ul>
        <li>
            <a href="{% url 'modis:source' %}">
                Sources
            </a>
        </li>
        <li>
            <a href="{% url 'modis:product' %}">
                Products
            </a>
        </li>
        <li>
            <a href="{% url 'modis:dataset' %}">
                DataSets
            </a>
        </li>
        <li>
            <a href="{% url 'modis:span' %}">
                Spans
            </a>
        </li>
        <li>
            <a href="{% url 'modis:getmodis' %}">
                Получить снимки MODIS и опубликовать их
            </a>
        </li>
        <li>
            <a href="{% url 'modis:viewmodis' %}">
                Просмотр снимков
            </a>
        </li>
    </ul>
{% endblock %}

web/modis/templates/modis/product_form.html
{% extends 'base.html' %}
{% block title %}
    Создать Product
{% endblock %}
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <form class="form-horizontal" action="" method="post">
                            {% csrf_token %}
                            {% include 'form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Сохранить</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

web/modis/templates/modis/source_form.html
{% extends 'base.html' %}
{% block title %}
    Создать Source
{% endblock %}
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <form class="form-horizontal" action="" method="post">
                            {% csrf_token %}
                            {% include 'form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Сохранить</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

web/modis/templates/modis/span_form.html
{% extends 'base.html' %}
{% block title %}
    Создать Span
{% endblock %}
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <form class="form-horizontal" action="" method="post">
                            {% csrf_token %}
                            {% include 'form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Сохранить</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}